import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

const DRAFT_AUTOGENERATED_RE = /PENDIENTE\s*[—–-]\s*draft autogenerado el (\d{4}-\d{2}-\d{2})/i;
const HUMAN_REVIEW_RE = /\*\*Última revisión humana\*\*:\s*(\d{4}-\d{2}-\d{2})/;

function diffDays(dateA, dateB) {
  const msPerDay = 1000 * 60 * 60 * 24;
  return Math.floor((dateA.getTime() - dateB.getTime()) / msPerDay);
}

export async function generateFreshnessReport({ kbRoot, stateDir, format, today = new Date() }) {
  const indexPath = join(kbRoot, 'indice.json');
  const sourcesPath = join(kbRoot, 'tools/scraper/sources.json');

  if (!existsSync(indexPath)) throw new Error(`indice.json no encontrado en ${kbRoot}`);
  if (!existsSync(sourcesPath)) throw new Error(`sources.json no encontrado en ${sourcesPath}`);

  const indice = JSON.parse(await readFile(indexPath, 'utf8'));
  const sourcesData = JSON.parse(await readFile(sourcesPath, 'utf8'));

  const items = (indice.items || []).filter(i => i.path && i.path.endsWith('.md'));
  const results = [];

  for (const item of items) {
    const mdPath = join(kbRoot, item.path);
    let mdContent = '';
    if (existsSync(mdPath)) {
      mdContent = await readFile(mdPath, 'utf8');
    }

    // Calcular Staleness Humano
    let humanDate = null;
    let isDraft = false;
    let reviewStatus = 'Sin revisión';

    const draftMatch = mdContent.match(DRAFT_AUTOGENERATED_RE);
    if (draftMatch) {
      isDraft = true;
      humanDate = new Date(draftMatch[1]);
      reviewStatus = 'Draft autogenerado';
    } else {
      const reviewMatch = mdContent.match(HUMAN_REVIEW_RE);
      if (reviewMatch) {
        humanDate = new Date(reviewMatch[1]);
        reviewStatus = 'Revisado';
      } else {
        reviewStatus = 'Pendiente / N/D';
      }
    }

    let humanStalenessDays = humanDate && !Number.isNaN(humanDate.getTime()) 
      ? diffDays(today, humanDate) 
      : Infinity;

    // Buscar el source y el meta.json
    let metaPath = null;
    let source = sourcesData.sources.find(s => s.indice_path === item.path);
    
    if (!source && item.path.startsWith('cursos/')) {
      source = sourcesData.sources.find(s => s.slug === 'cursos-de-formacion');
    }
    
    if (source) {
      if (source.slug === 'cursos-de-formacion') {
        metaPath = join(stateDir, 'cursos-de-formacion/cursos-de-formacion.meta.json');
      } else if (source.slug.startsWith('estudiantes-')) {
        metaPath = join(stateDir, 'estudiantes/estudiantes.meta.json');
      } else {
        metaPath = join(stateDir, `${source.slug}.meta.json`);
      }
    }

    let autoDate = null;
    if (metaPath && existsSync(metaPath)) {
      try {
        const meta = JSON.parse(await readFile(metaPath, 'utf8'));
        const dateStr = meta.last_checked_at || meta.scraped_at;
        if (dateStr) autoDate = new Date(dateStr);
      } catch {
        // Ignorar meta corrupto
      }
    }

    let autoStalenessDays = autoDate && !Number.isNaN(autoDate.getTime())
      ? diffDays(today, autoDate)
      : Infinity;

    results.push({
      path: item.path,
      title: item.title || item.path,
      category: item.category,
      reviewStatus,
      isDraft,
      humanStalenessDays,
      autoStalenessDays,
      humanDateStr: humanDate && !Number.isNaN(humanDate.getTime()) ? humanDate.toISOString().slice(0, 10) : 'N/D',
      autoDateStr: autoDate && !Number.isNaN(autoDate.getTime()) ? autoDate.toISOString().slice(0, 10) : 'N/D',
    });
  }

  // Ordenar: Primero los drafts más viejos, luego los no revisados, luego los revisados más viejos
  results.sort((a, b) => {
    // Prioridad 1: Drafts y Sin revisión primero
    const aPriority = a.isDraft || a.reviewStatus.includes('Sin') || a.reviewStatus.includes('Pendiente') ? 0 : 1;
    const bPriority = b.isDraft || b.reviewStatus.includes('Sin') || b.reviewStatus.includes('Pendiente') ? 0 : 1;
    if (aPriority !== bPriority) return aPriority - bPriority;
    
    // Prioridad 2: Mayor staleness humano
    if (a.humanStalenessDays !== b.humanStalenessDays) {
      return b.humanStalenessDays - a.humanStalenessDays;
    }
    
    // Prioridad 3: Mayor staleness automático
    if (a.autoStalenessDays !== b.autoStalenessDays) {
      return b.autoStalenessDays - a.autoStalenessDays;
    }
    
    return a.path.localeCompare(b.path);
  });

  if (format === 'json') {
    return JSON.stringify(results, null, 2);
  }

  if (format === 'md') {
    return generateMarkdown(results, today);
  }

  return generateConsoleTable(results);
}

function generateMarkdown(results, today) {
  const lines = [
    '# Reporte de Freshness de la Base de Conocimientos',
    '',
    `**Generado el:** ${today.toISOString().slice(0, 10)}`,
    '',
    '| Archivo | Estado | Días s/ Revisión Humana | Días s/ Scraping Automático |',
    '|---|---|---|---|'
  ];

  for (const r of results) {
    const humanIcon = r.humanStalenessDays > 180 ? '🔴' : (r.isDraft ? '🟡' : '🟢');
    const autoIcon = r.autoStalenessDays > 14 ? '🔴' : '🟢';
    
    const humanStr = r.humanStalenessDays === Infinity ? 'N/D' : `${r.humanStalenessDays} d (${r.humanDateStr})`;
    const autoStr = r.autoStalenessDays === Infinity ? 'N/D' : `${r.autoStalenessDays} d (${r.autoDateStr})`;
    
    lines.push(`| \`${r.path}\` | ${r.reviewStatus} | ${humanIcon} ${humanStr} | ${autoIcon} ${autoStr} |`);
  }

  return lines.join('\n');
}

function generateConsoleTable(results) {
  const maxPath = Math.max(...results.map(r => r.path.length), 10);
  
  const lines = [];
  lines.push(`\nFreshness Report (${results.length} archivos)`);
  lines.push('='.repeat(maxPath + 70));
  lines.push(
    'Path'.padEnd(maxPath + 2) + 
    'Estado'.padEnd(20) + 
    'Rev. Humana'.padEnd(20) + 
    'Scraping Auto'.padEnd(20)
  );
  lines.push('-'.repeat(maxPath + 70));

  for (const r of results) {
    const humanStr = r.humanStalenessDays === Infinity ? 'N/D' : `${r.humanStalenessDays}d (${r.humanDateStr})`;
    const autoStr = r.autoStalenessDays === Infinity ? 'N/D' : `${r.autoStalenessDays}d (${r.autoDateStr})`;
    
    lines.push(
      r.path.padEnd(maxPath + 2) + 
      r.reviewStatus.padEnd(20) + 
      humanStr.padEnd(20) + 
      autoStr.padEnd(20)
    );
  }
  lines.push('='.repeat(maxPath + 70) + '\n');
  return lines.join('\n');
}

async function main() {
  const { values } = parseArgs({
    options: {
      'kb-root': { type: 'string', default: '../..' },
      'state': { type: 'string', default: 'state' },
      'format': { type: 'string', default: 'table' },
      'out': { type: 'string' },
      help: { type: 'boolean', default: false },
    },
  });

  if (values.help) {
    console.log(`Sophia KB Freshness Report

Uso:
  node freshness_report.mjs [--kb-root=../..] [--format=table|md|json] [--out=report.md]

Opciones:
  --kb-root=<dir>     Raíz del repositorio KB (default: ../..)
  --state=<dir>       Directorio de estado del scraper (default: state)
  --format=<format>   Formato de salida: table, md, json (default: table)
  --out=<file>        Guardar salida en un archivo
`);
    process.exit(0);
  }

  const here = dirname(fileURLToPath(import.meta.url));
  const kbRoot = values['kb-root'].startsWith('/') ? values['kb-root'] : resolve(here, values['kb-root']);
  const stateDir = values.state.startsWith('/') ? values.state : resolve(here, values.state);

  try {
    const report = await generateFreshnessReport({
      kbRoot,
      stateDir,
      format: values.format,
    });

    if (values.out) {
      await writeFile(resolve(process.cwd(), values.out), report, 'utf8');
      console.log(`Reporte guardado en ${values.out}`);
    } else {
      console.log(report);
    }
    process.exit(0);
  } catch (err) {
    console.error(`Error: ${err.message}`);
    process.exit(1);
  }
}

const invokedDirectly = import.meta.url === `file://${process.argv[1]}`;
if (invokedDirectly) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
